<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0a67ec5b-e9bd-4b12-bfcf-1cfc4c660b33</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlcancIA.Application\AlcancIA.Application.csproj" />
    <ProjectReference Include="..\AlcancIA.Infrastructure\AlcancIA.Infrastructure.csproj" />
    <ProjectReference Include="..\AlcancIA.Domain\AlcancIA.Domain.csproj" />
  </ItemGroup>

</Project>
